apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
  namespace: default
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:80"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"
  USERS_API_URL: "http://users-api-service:80"
  USERS_API_TIMEOUT: "30"
