apiVersion: v1
kind: Service
metadata:
  name: catalog-api-service
  namespace: default
  labels:
    app: catalog-api
spec:
  type: LoadBalancer
  selector:
    app: catalog-api
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
